// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFvo56QBhZ1ayOvNaCz0AIOPlnzMOWKRA',
    appId: '1:904445767717:web:f4550082e99bade4e58fcc',
    messagingSenderId: '904445767717',
    projectId: 'health-care-chat-7f677',
    authDomain: 'health-care-chat-7f677.firebaseapp.com',
    storageBucket: 'health-care-chat-7f677.appspot.com',
    measurementId: 'G-HJF81QPZ4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCal1rZ7HVu3sa0L4jrCIXm5hUrGNp8POA',
    appId: '1:904445767717:android:4b3a133b592db514e58fcc',
    messagingSenderId: '904445767717',
    projectId: 'health-care-chat-7f677',
    storageBucket: 'health-care-chat-7f677.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3e3QEZbd022RztcyRxs9G8g6DyEyfbNg',
    appId: '1:904445767717:ios:894bd8ac8cdbfabae58fcc',
    messagingSenderId: '904445767717',
    projectId: 'health-care-chat-7f677',
    storageBucket: 'health-care-chat-7f677.appspot.com',
    iosBundleId: 'com.example.healthMate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3e3QEZbd022RztcyRxs9G8g6DyEyfbNg',
    appId: '1:904445767717:ios:894bd8ac8cdbfabae58fcc',
    messagingSenderId: '904445767717',
    projectId: 'health-care-chat-7f677',
    storageBucket: 'health-care-chat-7f677.appspot.com',
    iosBundleId: 'com.example.healthMate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFvo56QBhZ1ayOvNaCz0AIOPlnzMOWKRA',
    appId: '1:904445767717:web:071e332cb8854942e58fcc',
    messagingSenderId: '904445767717',
    projectId: 'health-care-chat-7f677',
    authDomain: 'health-care-chat-7f677.firebaseapp.com',
    storageBucket: 'health-care-chat-7f677.appspot.com',
    measurementId: 'G-YFVVLJNV09',
  );
}
